move /Y 3dSen-v1 /Files
move /Y Aquarius-BIOS-v1 /Files
move /Y Archimedes-BIOS-v1 /Files
move /Y Archmendes-BIOS-v1 /Files
move /Y Astrocade-BIOS-v1 /Files
move /Y cgenius-emu-v1 /Files
move /Y citron-emu-v1 /Files
move /Y clonehero-emu-v1 /Files
move /Y dolphin-bios-v1 /Files
move /Y DOSbox-Pure-MIDI-v1 /Files
move /Y Dragon-BIOS-v1 /Files
move /Y Dragon-BIOS-v2 /Files
move /Y ECWolf-BIOS-v1 /Files
move /Y eka-emu-v1 /Files
move /Y eka-v1 /Files
move /Y Electron-BIOS-v1 /Files
move /Y es-checkversion-v1 /Files
move /Y files.txt /Files
move /Y hotd2-bios-files-v1 /Files
move /Y Hypseus-v1 /Files
move /Y konami-LCD-artwork-v1 /Files
move /Y kronos-emu-v1 /Files
move /Y lime3ds-emu-v1 /Files
move /Y magicengine-emu-v1 /Files
move /Y mandarine-emu-v1 /Files
move /Y naomi-bios-files-v1 /Files
move /Y openjazz-emu-v1 /Files
move /Y paprium-core-v1 /Files
move /Y pdark-emu-v1 /Files
move /Y pinballfx-v1 /Files
move /Y PixN-Radio-v1 /Files
move /Y PixN-Radio-v2 /Files
move /Y PixN-Radio-v3 /Files
move /Y PixN-Radio-v4 /Files
move /Y PixN-Radio-v5 /Files
move /Y PixN-Stats /Files
move /Y pixn-us-check-v1 /Files
move /Y PS3-m3u-update-v1 /Files
move /Y Radio-v2 /Files
move /Y Radio-v3 /Files
move /Y Radio-v4 /Files
move /Y rb-7.3+bios_11-08-2025 /Files
move /Y rb-7.3+emulators_11-08-2025 /Files
move /Y rclone-v1 /Files
move /Y rclone-v2 /Files
move /Y rclone-v3 /Files
move /Y retroarch-emu-v1 /Files
move /Y ryujinx-emu-v1 /Files
move /Y ryujinx-emu-v2 /Files
move /Y Ryujinx-FW-v21.0.0 /Files
move /Y Set-PixN-Splash-v1 /Files
move /Y Set-PixN-Splash-v2 /Files
move /Y shadps4-emu-v1 /Files
move /Y shadps4-emu-v2 /Files
move /Y Sky-v1 /Files
move /Y solarus-emu-v1 /Files
move /Y Supracan-BIOS-v1 /Files
move /Y supracan-umc6650-v1 /Files
move /Y Switch-Eden-v1 /Files
move /Y Switch-v1 /Files
move /Y Switch-v2 /Files
move /Y TeknoParrot-v1 /Files
move /Y TeknoParrot-v2 /Files
move /Y TeknoParrot-v3 /Files
move /Y TeknoParrot-v4 /Files
move /Y TriForce-Config-v1 /Files
move /Y VPinball-v1 /Files
move /Y VPinball-v2 /Files
move /Y win98-bios-v1 /Files
move /Y win98-bios-v2 /Files
move /Y Xash3D-FWGS-v1 /Files
move /Y xenia-canary-emu-v1 /Files
move /Y xenia-canary-emu-v2 /Files
move /Y xenia-emu-v1 /Files
move /Y xenia-emu-v2v
move /Y xenia-manager-emu-v1 /Files
move /Y yabasanshiro-emu-v1 /Files
move /Y ZP-v1 /Files
exit